name: bot_io
version: 0.23.3
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot_io.dart
documentation: http://kevmoo.github.io/bot_io.dart
environment:
  sdk: '>=0.8.6'
dependencies:
  args: '>=0.8.6'
  bot: '>=0.24.0'
  crypto: '>=0.8.6'
  logging: '>=0.8.6'
  meta: '>=0.8.6'
  path: '>=0.8.6'
dev_dependencies:
  bot_test: '>=0.1.2'
  hop: '>=0.25.1'
  unittest: '>=0.8.6'
