name: bot_io
version: 0.20.0-dev.1
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
documentation: http://kevmoo.github.io/bot.dart
environment:
  sdk: '>=0.4.7+1'
dependencies:
  unittest: '>=0.4.7+1'
  bot: '>=0.20.0-dev'
  args: '>=0.4.7+1'
  logging: '>=0.4.7+1'
  pathos: '>=0.4.7+1'
  meta: '>=0.4.7+1'
dev_dependencies:
  html5lib: '>=0.4.3'
  hop: '>=0.20.0'
