name: git
version: 0.2.0
author: Kevin Moore <github@j832.com>
description: A dart wrapper around the git command line
homepage: https://github.com/kevmoo/git.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.27.0'
  bot_io: '>=0.25.1 <0.27.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  bot_test: '>=0.1.5'
  hop: '>=0.28.1+2'
  unittest: '>=0.10.0 <0.11.0'
