name: git
version: 0.4.2-dev
author: Kevin Moore <github@j832.com>
description: A Dart wrapper around the Git command line
homepage: https://github.com/kevmoo/git.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.29.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  hop: '>=0.30.4+1 <0.32.0'
  hop_unittest: '>=0.1.0 <0.2.0'
  scheduled_test: '>=0.10.0 <0.12.0'
