name: git
version: 0.4.1
author: Kevin Moore <github@j832.com>
description: A dart wrapper around the git command line
homepage: https://github.com/kevmoo/git.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.26.0 <0.28.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  hop: '>=0.30.4+1 <0.31.0'
  hop_docgen: '>=0.1.2+5 <0.2.0'
  scheduled_test: '>=0.10.0 <0.12.0'
