name: bot_io
version: 0.21.1-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot_io.dart
documentation: http://kevmoo.github.io/bot_io.dart
environment:
  sdk: '>=0.4.7+1'
dependencies:
  args: '>=0.4.7+1'
  bot: '>=0.20.1'
  logging: '>=0.4.7+1'
  meta: '>=0.4.7+1'
  pathos: '>=0.4.7+1'
  unittest: '>=0.4.7+1'
dev_dependencies:
  hop: '>=0.21.0'
  html5lib: '>=0.4.3'
