name: bot_io
version: 0.23.2-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot_io.dart
documentation: http://kevmoo.github.io/bot_io.dart
environment:
  sdk: '>=0.6.13'
dependencies:
  args: '>=0.6.13'
  bot: '>=0.23.0'
  crypto: '>=0.6.13'
  logging: '>=0.6.13'
  meta: '>=0.6.13'
  path: '>=0.6.13'
dev_dependencies:
  bot_test: '>=0.1.2'
  hop: '>=0.24.1+1'
  html5lib: '>=0.4.4'
  unittest: '>=0.6.13'
